name: Playwright Smoke Tests

on:
  workflow_dispatch: # permite ejecución manual
  push:               # Or trigger on push to the repository
    branches:
      - main

jobs:
  run-smoke-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Smoke Tests
        run: npx playwright test tests/smoke.spec.ts --reporter html

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@main
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 30
